@startuml

Document o-- "n" Section
Section -- "n" Section
Section o-- "n" Element
Element -- ElemType

class Document {
    str template
    str[] states
    str[] styles
}

class Section {
    str id
}

class Element {
    str value
}

enum ElemType {
    LABEL, 
    BUTTON, 
    INPUT-TEXT, 
    INPUT-EMAIL, 
    INPUT-SECRET, 
    CHECKBOX, 
    RADIO, 
    DROP-DOWN, 
    TABLE...
}



@enduml