@startuml "project"

    interface Reader {
        read()
    }

    class FileReader implements Reader {
    }

    interface Parser<T> {
        parse(): T
    }

    class YaProtoParser implements Parser {
    }

    interface Renderer<T> {
        render(T): Stream
    }

    class HtmlRenderer implements Renderer {
    }

    interface HtmlComponentDecorator extends Component {
    }

    class Executor {
        execute(file: str)
    }

    Executor .. Reader
    Executor .. Parser
    Executor .. Renderer
    Renderer .. HtmlComponentDecorator

@enduml